# Generated by Django 5.1.3 on 2024-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occur_country', models.CharField(blank=True, max_length=100, null=True)),
                ('active_substance', models.CharField(blank=True, max_length=255, null=True)),
                ('drug_dosage_form', models.CharField(blank=True, max_length=255, null=True)),
                ('drug_dosage_text', models.TextField(blank=True, null=True)),
                ('drug_indication', models.TextField(blank=True, null=True)),
                ('medicinal_product', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_sex', models.IntegerField(blank=True, null=True)),
                ('reporter_country', models.CharField(blank=True, max_length=100, null=True)),
                ('seriousness_death', models.IntegerField(blank=True, null=True)),
                ('seriousness_disabling', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AspirinData',
        ),
    ]
